settings:
  test_enabled: True
  bank_name: AwesomeGIC Bank
  production: False
  menu_transaction: Input transactions
  menu_rules: Define interest rules
  menu_statement: Print statement
  menu_quit: Quit
  menu_continue: Is there anything else you'd like to do?
  account_title: Account
  interest_rule_title: Interest rules
  date_col: Date
  tansaction_col: Txn Id
  type_col: Type
  amount_col: Amount
  balance_col: Balance
  rule_col: RuleId
  rate_col: Rate (%)
  transaction_input: Please enter transaction details in <Date> <Account> <Type> <Amount> format
  rule_input: Please enter interest rules details in <Date> <RuleId> <Rate in %> format
  print_input: Please enter account and month to generate the statement <Account> <Year><Month>
  empty_input: (or enter blank to go back to main menu)

postgresql:
  database: localhost
  user: admin
  password: admin
  host: xxx.ap-southeast-1.rds.amazonaws.com
  port: 5432
  sslmode: require